Ed-Fi-Exchange-OSS/EdFi-Project-Buzz

EdFi.Buzz.UI.Angular/src/app/Features/StudentDetail/studentDetail.component.html
EdFi.Buzz.UI.Angular/src/app/Features/StudentDetail/studentDetail.component.ts
EdFi.Buzz.UI.Angular/src/app/Services/GraphQL/studentNotesMutations.ts
EdFi.Buzz.UI.Angular/src/app/Services/studentNotes.service.ts

[FIF-167] Adds delete student notes feature to the front-end.

---

EdFi.Buzz.Database/migrations/20200729161015-create-jobstatus-tables.js
EdFi.Buzz.Database/migrations/sqls/20200729161015-create-jobstatus-tables-down.sql
EdFi.Buzz.Database/migrations/sqls/20200729161015-create-jobstatus-tables-up.sql

Added new tables:
- JobStatus: Lookup table.
- SurveyStatus.

[FIF-204] Database schema migration: SurveyStatus

---

.teamcity/ETL/Project.kt
.teamcity/ETL/buildTypes/BranchETLBuild.kt
.teamcity/ETL/buildTypes/DeployETL.kt
.teamcity/ETL/buildTypes/PullRequestETLBuild.kt
CONTRIBUTORS.md
EdFi.Buzz.Etl/eng/Windows/EdfiBuzzEtl.xml
EdFi.Buzz.Etl/eng/Windows/install.md
EdFi.Buzz.Etl/eng/Windows/install.ps1
EdFi.Buzz.Etl/eng/build-package.ps1
EdFi.Buzz.Etl/eng/build.js
EdFi.Buzz.Etl/eng/edfi.buzz.etl.nuspec
EdFi.Buzz.Etl/package.json
EdFi.Buzz.Etl/yarn.lock

This PR adds a Team City build for the ETL project with a NuGet archive artifact.

[FIF-213] Add TeamCity build project for ETL

---

EdFi.Buzz.Api/src/graphql/entities/queues/taskitem.entity.ts
EdFi.Buzz.Api/src/graphql/services/taskitem.service.ts
EdFi.Buzz.Etl/config/jobStatusEnum.js
EdFi.Buzz.Etl/processors/surveyProcessor.js
EdFi.Buzz.Etl/tasks/buzzSurvey.js

- Added job key to payload to link current task with the job row.
- Added database statement to update status to processing and complete during survey process.

[FIF-206] ETL to write to the new Schema Objects

---

EdFi.Buzz.Etl/package.json
EdFi.Buzz.Etl/yarn.lock
README.md

Standardization of build scripts

---

EdFi.Buzz.Api/src/graphql/entities/survey/answersbystudent.entity.ts
EdFi.Buzz.Api/src/graphql/entities/survey/studentsurvey.entity.ts
EdFi.Buzz.Api/src/graphql/entities/survey/survey.entity.ts
EdFi.Buzz.Api/src/graphql/entities/survey/surveyquestion.entity.ts
EdFi.Buzz.Api/src/graphql/entities/survey/surveystatus.entity.ts
EdFi.Buzz.Api/src/graphql/graphql.schema.ts
EdFi.Buzz.Api/src/graphql/schema/schema.graphql
EdFi.Buzz.Api/src/graphql/services/studentsurvey.service.ts
EdFi.Buzz.Api/src/graphql/services/taskitem.service.ts

Updated survey key datatype to int.
Fixed API taskitem.entity lint issue.

[FIF-234] API: The surveykey field must be numeric

---

.teamcity/_Self/Project.kt
EdFi.Buzz.Etl/eng/Windows/EdfiBuzzEtl.xml
EdFi.Buzz.Etl/eng/Windows/install.ps1
EdFi.Buzz.Etl/package.json
EdFi.Buzz.Etl/processors/surveyProcessor.js
EdFi.Buzz.Etl/yarn.lock
README.md

Need to add ETL as subproject.

[FIF-213] Fix to add ETLProject to Kotlin to create subproject

---

EdFi.Buzz.UI.Angular/src/app/Features/navbar/navbar.component.html

- Update navbar.component.html
- Fixed option to show option 'Admin. surveys' only for admin users.

[FIF-236] Admin surveys link shows for non-admin users

---

EdFi.Buzz.Api/src/graphql/graphql.schema.ts
EdFi.Buzz.Api/src/graphql/resolvers/survey.resolver.ts
EdFi.Buzz.Api/src/graphql/schema/schema.graphql
EdFi.Buzz.Api/src/graphql/services/survey.service.ts
EdFi.Buzz.Api/src/graphql/services/surveystatus.service.ts
EdFi.Buzz.UI.Angular/src/app/AdminSurvey/adminSurvey.component.html
EdFi.Buzz.UI.Angular/src/app/AdminSurvey/adminSurvey.component.ts
EdFi.Buzz.UI.Angular/src/app/Models/survey.ts
EdFi.Buzz.UI.Angular/src/app/Services/GraphQL/surveyMutations.ts
EdFi.Buzz.UI.Angular/src/app/Services/survey.service.ts

@kurtjohnson-HS  Notice that this is deleting a survey, not updating it. If you go to the admin survey page, you should see a red button at the bottom of the survey result. Let me attach a couple of screenshots.

[FIF-193] Adds delete survey to the UI

---

EdFi.Buzz.Etl/processors/surveyProcessor.js

Remove TODO comments from survey processor

Remove comments

---

EdFi.Buzz.Database/eng/Windows/install.ps1
EdFi.Buzz.Database/package.json

Added db-migrate db:create. The database will be created if it does not exist.

[FIF-249] Database installation creates the database if it does not exist

---

EdFi.Buzz.UI.Angular/src/app/Components/SearchInSectionsUIReact/searchInSections.tsx
EdFi.Buzz.UI.Angular/src/app/Features/SurveyAnalyticsReact/surveyAnalyticsReactWrapper.tsx

This task is for adding the fonts component and styled-components ThemeProvider to the SurveyAnalytics.

[FIF-238] Wrap the React survey with theme

---

EdFi.Buzz.Api/package.json
EdFi.Buzz.Api/src/app.module.ts
EdFi.Buzz.Api/src/graphql/decorators/currentUser.decorator.ts
EdFi.Buzz.Api/src/graphql/guards/validateStaffId.guard.ts
EdFi.Buzz.Api/yarn.lock

Fix API 500 error. 
This error is caused by changes in a platform-@nestjs/platform-fastify@^7.4.4 dependency (fastify "3.3.0")
- Do a yarn install in API
- API and UI should work

[FIF-312] Investigate why the app is throwing an 500 error. And fix it

---

EdFi.Buzz.Api/package.json
EdFi.Buzz.Api/src/app.module.ts
EdFi.Buzz.Api/src/graphql/decorators/currentUser.decorator.ts
EdFi.Buzz.Api/src/graphql/guards/validateStaffId.guard.ts
EdFi.Buzz.Api/yarn.lock
EdFi.Buzz.UI/src/Feature/StudentRoster/index.tsx

Validation to avoid the problem Throwing an exception that the sectionkey is undefined when the user has no students or sections.

[FIF-309] Adding validation when Section list is null

---

EdFi.Buzz.UI/src/Feature/Login/index.tsx

Added a message when a user doesn't exist in Buzz database.
Given an unregistered user, when they redirect from the SSO login, it shows a message that the user is not registered

[FIF-201] Redirect authenticated users who are not in the system

---

EdFi.Buzz.Installer/eng/README.md

A new readme file was created to include the global installer instructions.

[FIF-261] Added the readme file the global installer

---

EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Components/Footer/index.tsx

Mobile styles
- Removed horizontal scroll.
- Added left and right margins.

[FIF-311] Updated mobile style margins.

---

EdFi.Buzz.UI/package.json
EdFi.Buzz.UI/src/DIContext.ts
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyChartAndTable.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyWordCloud.tsx
EdFi.Buzz.UI/yarn.lock

1) Added the wordcloud when a survey question has 10 or more questions.

[FIF-65] Added word cloud for open ended survey questions

---

EdFi.Buzz.Database/eng/Windows/install.ps1
EdFi.Buzz.Database/migrations/sample-data/20201022195215-adds-sample-data.js
EdFi.Buzz.Database/migrations/sample-data/sqls/20201022195215-adds-sample-data-down.sql
EdFi.Buzz.Database/migrations/sample-data/sqls/20201022195215-adds-sample-data-up.sql
EdFi.Buzz.Database/package.json
EdFi.Buzz.Installer/eng/Windows/AppSharedLibrary/Buzz-App-Install.psm1
EdFi.Buzz.Installer/eng/Windows/Application/appinstalls.psm1
EdFi.Buzz.Installer/eng/Windows/configHelper.psm1
EdFi.Buzz.Installer/eng/Windows/example.configuration.json
EdFi.Buzz.Installer/sampleDataSeed/sampleData.sql

I have added a new migration to the database project. This new script is not part of the default collection. We are using the scoping feature of the db-migrate tool to conditionally execute it. 
A new flag value has been added to the **example.configuration.json** file with the name **loadSampleData**. 
To test it, just execute an installation after changing the **loadSampleData** value in your local **configuration.json** file.
Based on this configuration value, the database should or shouldn't have the sample data.

[FIF-314] Public Demo Site - Reset Data.

---

EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Feature/Login/index.tsx
EdFi.Buzz.UI/src/Feature/Privacy/index.tsx

It can be accessed through the link available on the login screen

[FIF-343] Added Privacy Policy Page

---

EdFi.Buzz.UI/src/App.tsx

Was using an empty dependency array that fired on every change.

[FIF-356] Update React UI App Effect hook

---

EdFi.Buzz.UI/src/Components/Header/index.tsx

- Gradient from #333333 to #000000
Header
Menu

[FIF-105] Header background color updated for better contrast.

---

EdFi.Buzz.UI/src/Components/Header/index.tsx
EdFi.Buzz.UI/src/Components/Header/loadodssurvey.tsx

Once you log in, you should be able to access the header menu by pressing the tab key. Notice that you can access the different pages by pressing enter. You can access the logged in user menu using the enter key as well.

[FIF-338] Makes user name menu accessible by the keyboard.

---

EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Components/Header/index.tsx
EdFi.Buzz.UI/src/Feature/AdminSurvey/index.tsx
EdFi.Buzz.UI/src/__mocks__/@iconify-icons/ion/add.js

[FIF-349] Move upload surveys to inside of survey administration

---

EdFi.Buzz.Etl/config/etl.js

There was a build error on the merge to main. Trailing comma issue.

[FIF-358] Lint etl files

---

EdFi.Buzz.UI/src/DIContext.ts
EdFi.Buzz.UI/src/Feature/StudentDetail/StudentDetailAssessment.tsx
EdFi.Buzz.UI/src/Feature/StudentDetail/index.tsx
EdFi.Buzz.UI/src/Models/Assessment.ts
EdFi.Buzz.UI/src/Models/index.ts
EdFi.Buzz.UI/src/Services/ApiService.ts
EdFi.Buzz.UI/src/Services/AssessmentService.ts
EdFi.Buzz.UI/src/Services/GraphQL/AssessmentQueries.ts

The new option shows the assessments by student, in case you have registered any.
- A student must be selected from the list to enter StudentDetails.
- In StudentDetails, if the student has Assessments, a tab will appear.
- By pressing the tab, the list of registered Assessments should appear.

[FIF-360] Create the UI to show assessment data

---

EdFi.Buzz.Database/migrations/20201204200949-create-demographics-tables.js
EdFi.Buzz.Database/migrations/sqls/20201204200949-create-demographics-tables-down.sql
EdFi.Buzz.Database/migrations/sqls/20201204200949-create-demographics-tables-up.sql

Execute yarn migrate to execute the new migration. 3 new tables should be created and one of them should have 2 rows already inserted.

[FIF-367] Creates a Buzz database structure to hold demographic information.

---

EdFi.Buzz.Api/src/app.module.ts
EdFi.Buzz.Api/src/graphql/entities/buzz/demographics.entity.ts
EdFi.Buzz.Api/src/graphql/entities/buzz/demographicstype.entity.ts
EdFi.Buzz.Api/src/graphql/entities/buzz/index.ts
EdFi.Buzz.Api/src/graphql/entities/buzz/studentdemographics.entity.ts
EdFi.Buzz.Api/src/graphql/entities/buzz/studentschool.entity.ts
EdFi.Buzz.Api/src/graphql/graphql.schema.ts
EdFi.Buzz.Api/src/graphql/modules/demographics.module.ts
EdFi.Buzz.Api/src/graphql/modules/studentschool.module.ts
EdFi.Buzz.Api/src/graphql/resolvers/demographics.resolver.ts
EdFi.Buzz.Api/src/graphql/resolvers/studentschool.resolver.ts
EdFi.Buzz.Api/src/graphql/schema/schema.graphql
EdFi.Buzz.Api/src/graphql/services/demographics.service.ts

At this point we don't have yet the ETL working and we don't have sample data. So, I will include scripts to insert data into the corresponding tables. 
1. My recommendation is to use a database with the sample data we have in our database project.
2. Then execute this script to have data into the corresponding tables.
```
INSERT INTO buzz.demographics(
shortdescription, demographicstypekey)
VALUES ('Characteristic 1', 1);
INSERT INTO buzz.demographics(
shortdescription, demographicstypekey)
VALUES ('Characteristic 2', 1);
INSERT INTO buzz.demographics(
shortdescription, demographicstypekey)
VALUES ('Program 1', 2);
INSERT INTO buzz.demographics(
shortdescription, demographicstypekey)
VALUES ('Program 2', 2);
--	
INSERT INTO buzz.studentdemographics(
demographicskey, studentschoolkey) …
```

[FIF-365] Creates an API to expose student demographics to the UI.

---

EdFi.Buzz.UI/src/DIContext.ts
EdFi.Buzz.UI/src/Feature/StudentDetail/StudentDetailDemographics.tsx
EdFi.Buzz.UI/src/Feature/StudentDetail/index.tsx
EdFi.Buzz.UI/src/Models/Demographic.ts
EdFi.Buzz.UI/src/Models/index.ts
EdFi.Buzz.UI/src/Services/ApiService.ts
EdFi.Buzz.UI/src/Services/DemographicsService.ts
EdFi.Buzz.UI/src/Services/GraphQL/DemographicsQueries.ts

In summary what we need is to access the student details page to see the demographic information. 
From the data perspective there are 2 ways we can do that.
1. Execute the ETL to make sure that you have data locally. Notice that not necessarily every student has demographic information.
2. (The easy way) Execute the sample data script in our database project. Every student has demographic information.

[FIF-364] Creates UI to show student demographics.

---

EdFi.Buzz.Api/package.json
EdFi.Buzz.Api/yarn.lock
EdFi.Buzz.UI/package.json
EdFi.Buzz.UI/yarn.lock

- For each of the projects run 'yarn audit'. The result should be that there are no detected vulnerabilities.
- Run the installation script, no component should show vulnerabilities

[FIF-313] Updated to fix audit warning messages.

---

EdFi.Buzz.Api/package.json
EdFi.Buzz.Api/yarn.lock
EdFi.Buzz.Etl/package.json
EdFi.Buzz.Etl/yarn.lock
EdFi.Buzz.UI/package.json
EdFi.Buzz.UI/yarn.lock

[FIF-399] Resolve Project Buzz dependabot alerts
