EdFi.Buzz.Etl/README.md
EdFi.Buzz.Etl/package.json
EdFi.Buzz.Etl/tasks/surveyLoader.js
EdFi.Buzz.Etl/yarn.lock

Adds the graphile-worker and a rudimentary hello world task. Also updates the ETL Readme with the following additional instructions to execute the ETL as a service.
Graphile Worker allows the ETL to run as a service. It will watch the graphile-worker jobs table for new jobs. The initial execution creates the required database schema objects needed to manage jobs. In production, the Project Buzz API will manage creating new survey jobs to process. Use the testing step below to add an individual survey for processing.
```bash
$ cd edfi.buzz.etl
$ npx graphile-worker -c "postgres://user:password@database.url:port/edfi_buzz"
```
The surveyRunner task can execute a survey job manuall. Run the following SQL and replace the example staffkey,  survey name and file path location.
Once the …

[FIF-181] Add graphile-worker

---

EdFi.Buzz.Api/src/graphql/entities/studentnote.entity.ts
EdFi.Buzz.Api/src/graphql/graphql.schema.ts
EdFi.Buzz.Api/src/graphql/resolvers/studentnote.resolver.ts
EdFi.Buzz.Api/src/graphql/schema/schema.graphql
EdFi.Buzz.Api/src/graphql/services/studentnote.service.ts
EdFi.Buzz.Api/src/graphql/services/studentschool.service.ts
EdFi.Buzz.Database/migrations/20200728092015-adds-delete_at-colum-to-studentnote-table.js
EdFi.Buzz.Database/migrations/sqls/20200728092015-adds-delete_at-colum-to-studentnote-table-down.sql
EdFi.Buzz.Database/migrations/sqls/20200728092015-adds-delete_at-colum-to-studentnote-table-up.sql

- Two columns were added to StudentNote:
1. deletedat: The date it was deleted.
2. deletedby: The staffkey of who deleted it.
- Deletestudentnote method added to do the API.
- The notes query was modified to return only those that do not have a deletion date.

[FIF-198] Soft delete student notes - backend

---

EdFi.Buzz.Api/src/graphql/entities/staff.entity.ts
EdFi.Buzz.Api/src/graphql/schema/schema.graphql
EdFi.Buzz.Database/migrations/20200728093327-adds-isteachersurveyloader-column-to-staff-table.js
EdFi.Buzz.Database/migrations/sqls/20200728093327-adds-isteachersurveyloader-column-to-staff-table--down.sql
EdFi.Buzz.Database/migrations/sqls/20200728093327-adds-isteachersurveyloader-column-to-staff-table--up.sql
EdFi.Buzz.Etl/README.md
EdFi.Buzz.Etl/package.json
EdFi.Buzz.Etl/processors/surveyProcessor.js
EdFi.Buzz.Etl/yarn.lock
EdFi.Buzz.UI.Angular/src/app/Features/navbar/navbar.component.html
EdFi.Buzz.UI.Angular/src/app/Interceptors/auth.guard.ts
EdFi.Buzz.UI.Angular/src/app/Models/teacher.ts
EdFi.Buzz.UI.Angular/src/app/Services/GraphQL/staffQueries.ts

When this PR is applied, it will allow admin users to upload surveys for all students without restrictions. Existing functionality for teachers should continue to restrict the target of their updates to only their students.
The PR makes the following modifications:
- adds a isteachersurveyloader boolean column to the staff table via a new database migration.
- replaces the original usages of isadminsurveyloader with isteachersurveyloader
- updates navigation for survey loader menu to check permissions for both teachers and administrator survey loaders.
- updates the ETL's survey processor query for when to update a student with a union query for staff with the survey loading administrator user permission set to true. And it updates the original teacher query to replace the admin …

[FIF-197] Give administrator users ability to upload surveys

---

EdFi.Buzz.Database/eng/Windows/install.md
README.md

Our main readme does not mention why we have README and install markdown files, or their purpose. This PR updates the install instructions specific to the database project and adds a list of our READMEs to distinguish them from install instructions.

[FIF 244] Update the main README to reduce confusion with install instructions

---

EdFi.Buzz.UI.Angular/src/app/Features/SurveyAnalyticsReact/surveyChart.tsx

The survey page is clipping the right side of the tooltip.
This PR will add a layout option configuration to add some padding to the right side. To look as it does below...

[FIF-237] Fix chart-js clipping on the tooltip on surveys

---

EdFi.Buzz.Database/migrations/20200827142743-adds-note-visibility.js
EdFi.Buzz.Database/migrations/sqls/20200827142743-adds-note-visibility-down.sql
EdFi.Buzz.Database/migrations/sqls/20200827142743-adds-note-visibility-up.sql

Adds the field `visibleonlytoauthor` to set the visibility of the note:
* false: default, visible to all staff that can view the student's details.
* true: Only visible to the note's author.
* Run `yarn migrate` in the `EdFi.Buzz.Database` directory.
* In app: 
* Add a note to a student. *Should not fail*.
* Delete a note from a student. *Should not fail*.

[FIF-155] Configurable Note visibility - Schema Update

---

EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Services/EnvironmentService.ts

Fixed errors on EnvironmentService.
Disabled linting on App to prevent an error
KNOWN ISSUE: We are testing successfully locally. The build passes on TeamCity, but "Error message is logged" message causes the tests to "fail".

[FIF-279] Skip linting the environment service and app lines

---

EdFi.Buzz.UI/.eslintrc.json
EdFi.Buzz.UI/package.json
EdFi.Buzz.UI/yarn.lock

React's eslint rules configuration is has more restrictions than what we had on Angular. This PR will change the current errors into warnings, and add TODO comments to the eslintrc.json. The task to fix linting issues #FIF-302 was documented with all of these rules changes.

[FIF-279] Show warn instead of error on eslint issues

---

EdFi.Buzz.UI/.jest/setupFile.js
EdFi.Buzz.UI/jest.config.js
EdFi.Buzz.UI/package.json
EdFi.Buzz.UI/src/App.test.tsx
EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Feature/Login/__mocks__/@iconify-icons/ion/md-lock.js
EdFi.Buzz.UI/src/Feature/Login/index.tsx
EdFi.Buzz.UI/src/Services/EnvironmentService.ts
EdFi.Buzz.UI/yarn.lock

The App test was failing for a couple of reasons. Now it passes again, but the tests fail TeamCity because of an output message.
TeamCity output messages are being used.
We didn't have mocks for iconify-icons called by Login feature. There is now a pattern for that.
.jest/setupFiles.js now has process.env set up.
There is a jest.config.js with configuration.

Fix app test

---

EdFi.Buzz.UI.Angular/package.json
EdFi.Buzz.UI.Angular/yarn.lock

node-forge has a high severity issue. It is in the yarn.lock for Angular. We have a transitive dependency on the package. We can use selective dependency resolution to force the upgrade.
Used [this](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) as a guide to update this dependency.

[FIF-305] Updating Angular to node-forge@0.10.0

---

EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Feature/UploadSurvey/index.tsx
EdFi.Buzz.UI/src/Services/SurveyService.ts

This will add survey upload page to the full react app
- /* eslint react-hooks/exhaustive-deps: "off"*/ was added because compiler complained about it in `useEffect` call asking to add `loadLastUploadedSurvey` and `PrepareIfUpdatingSurvey` to the dependencies list which make react re-render the component too many times.
- In .env it needs 
`REACT_APP_SURVEY_MAX_FILE_SIZE_BYTES=122400`
`REACT_APP_JOB_STATUS_FINISH_IDS=[3]`
- Upload surveys
- Update status
- Require survey title
- Check if file length is less than REACT_APP_SURVEY_MAX_FILE_SIZE_BYTES

[FIF-285] Move React components to EdFi.Buzz.UI - Upload survey

---

.teamcity/Installer/Project.kt
.teamcity/Installer/buildTypes/BranchInstallerBuild.kt
.teamcity/Installer/buildTypes/DeployInstaller.kt
.teamcity/Installer/buildTypes/PullRequestUIBuild.kt
.teamcity/_Self/Project.kt
EdFi.Buzz.Installer/build-package.ps1
EdFi.Buzz.Installer/edfi.buzz.nuspec
EdFi.Buzz.Installer/eng/Windows/install.ps1

This PR will provide a working teamcity build script and Nuget install script that both return exitcodes for success.
This should allow a developer to work TeamCity and a developer to create a locally runnable PowerShell Installer script in parallel.
NOTE: The new TeamCity build for this newly added Installer project will require a refresh of our Build project settings. Currently, it is not building. We should get a clean build.

[FIF-298] Create initial folder structure for Buzz Installer

---

EdFi.Buzz.UI/.eslintrc.json
EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Components/DataTable/dataTable.tsx
EdFi.Buzz.UI/src/Feature/Login/LoginADFS.tsx
EdFi.Buzz.UI/src/Feature/Login/SocialButton.tsx
EdFi.Buzz.UI/src/Feature/Login/index.tsx
EdFi.Buzz.UI/src/Feature/StudentDetail/index.tsx
EdFi.Buzz.UI/src/Feature/StudentRoster/index.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/index.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyChart.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyChartAndTable.tsx
EdFi.Buzz.UI/src/Feature/UploadSurvey/index.tsx
EdFi.Buzz.UI/src/Models/ResultSummaryObj.ts
EdFi.Buzz.UI/src/Models/StudentSurveySummaryAnswersProcess.ts
EdFi.Buzz.UI/src/Models/Survey.ts
EdFi.Buzz.UI/src/Models/SurveyStatus.ts
EdFi.Buzz.UI/src/Services/ApiService.ts
EdFi.Buzz.UI/src/Services/AuthenticationService.ts
EdFi.Buzz.UI/src/Services/GraphQL/SectionQueries.ts
EdFi.Buzz.UI/src/Services/SectionService.ts
EdFi.Buzz.UI/src/Services/StudentNotesService.ts
EdFi.Buzz.UI/src/Services/StudentService.ts
EdFi.Buzz.UI/src/Services/SurveyAnalyticsService.ts
EdFi.Buzz.UI/src/Services/SurveyService.ts
EdFi.Buzz.UI/src/Services/TeacherService.ts

I removed all the TODOs in the root linting configuration.
I had to keep some exception in specific cases, specially (but not exclusively) the any type.
Places where I had to keep the any type: datatable, loginADFS (2 lines), SocialButton. I used the eslint-disable-next-line option instead of disabling the rule for an entire file.
1. **StudentDetailSurvey**
```
/* eslint no-return-assign: "off"*/
survey.answers.map((a, index) => (
<StudentDetailSurveyAnswerRow key={index} idx={i += 1} answer={a} />
))}
```
For some reason eslint does not like the `i+=1`. Not sure why, because based on the documentation this is the right way to increment the value.
2. **UploadSurvey/index**
```
useEffect(() => {
loadLastUploadedSurvey();
/* eslint-disable-next-line react-hooks/exhaustive-deps */
}, []); …
```

[FIF-302] Fixes linting errors.

---

EdFi.Buzz.UI/src/App.tsx
EdFi.Buzz.UI/src/Components/Header/index.tsx
EdFi.Buzz.UI/src/__mocks__/@iconify-icons/ion/md-cloud-upload.js

The Upload Survey options was not added to the drop down menu. The solution included adding the menu option with the validations to show it when the **isAdminSurveyLoader** flag or the **isTeacherSurveyLoader** flag is on. 
Log in and log out to the app while you modify the staff.isadminsurveyloader and staff.isteachersurveyloader values in the database. See how the option menu to Upload Survey is shown or not. The menu option should be shown when one of these 2 values is on. 
Additionally try to access the Upload Survey page using the address bar.

[FIF-324] Adds Upload Survey option to the top-right drop down menu.

---

EdFi.Buzz.Api/src/graphql/services/jwt.service.ts

When using a google user who does not return mail to Buzz, an exception is generated in GetClaims. Updated to include exception handling.

[FIF-323] Updated exception handling for jwt GetClaims

---

EdFi.Buzz.UI/package.json

Dependabot left us a security message to upgrade jquery. 
~~I did that and discovered synp also had a low-risk fix needed.~~
~~Both are updated...~~
synp came up as a low level fix in the package audit but updating that causes TeamCity build errors. FIF-313 already should address this issue. I will update it to make sure it is included.

[FIF-329] Update jquery with a package resolution

---

EdFi.Buzz.UI/src/Components/Header/index.tsx
EdFi.Buzz.UI/src/Components/SearchInSections/searchInSections.tsx
EdFi.Buzz.UI/src/Feature/StudentRoster/studentCard.tsx

I am not sure if I am taking the right approach. Don't have much experience using the tab-index attribute. But it seems to be working fine. Tested it with Chrome, Firefox and Edge.
If this is not the right approach please feel free to point it out. 
1. Execute the app, log in and go to the roster page.
2. Click on the URL address bar
3. Start pressing tab and the focus should move this way:
3. a. Class Roster menu option, then Surveys and finally logged in user option.
3. b. Then it will move to the Filter by Class drop down and Search by Student Name input text.
3. c. After that the focus should move to the student card. First the picture, then the email, and then the View More menu option.
Notice that if you press enter on the View More option the card expands and collapses. 
Notice as …

[106] Makes the roster card -View More option- accessible by keyboard.

---

EdFi.Buzz.UI/src/Feature/StudentRoster/index.tsx

Execute the app, log in and go to the roster page.
Click on the URL address bar
Start pressing tab and the focus should move this way:
a. Class Roster menu option, then Surveys and finally logged in user option.
b. Then it will move to the Filter by Class drop down and Search by Student Name input text.
c. After that the focus should move to the View Style section. 
Notice that if you press enter on the Grid view or Cards view, the roster should change to that view.

[FIF-333] Makes Roster View Style accesible by the keyboard.

---

EdFi.Buzz.UI/src/Feature/StudentDetail/index.tsx

As I mentioned in the PR for FIF-106 and FIF-333, I am not sure if I am taking the right approach. Don't have much experience using the tab-index attribute. But it seems to be working fine. Tested it with Chrome, Firefox and Edge.
If this is not the right approach please feel free to point it out.
Execute the app, log in and go to the roster page and then go to the student detail page of any of the students.
Click on the URL address bar
Start pressing tab and the focus should move this way:
a. Class Roster menu option, then Surveys and finally logged in user option.
b. Then it will move to the student specific fields, first Go back to student roster link, then email.
c. After that the focus should move to the tabs: Survey tab and Notes tab.
Notice that if you press enter on the tabs, that …

[FIF-335] Makes Student detail survey and notes tabs accessible by the keyboard.

---

EdFi.Buzz.UI/src/Feature/StudentDetail/StudentDetailNote.tsx
EdFi.Buzz.UI/src/Feature/StudentDetail/StudentDetailNotesContainer.tsx
EdFi.Buzz.UI/src/Feature/StudentDetail/StudentDetailSurvey.tsx
EdFi.Buzz.UI/src/globalstyle.ts

Execute the app, log in and go to the roster page and then go to the student detail page of any of the students.
Click on the URL address bar
Start pressing tab and the focus should move this way:
a. Class Roster menu option, then Surveys and finally logged in user option.
b. Then it will move to the student specific fields, first Go back to student roster link, then email.
c. After that the focus should move to the tabs: Survey tab and Notes tab.
d. Finally, you should be able to move to the survey answers. 
e. Additionally, you should be able to go to the notes, add notes, delete notes, etc.

[FIF-334] Makes student detail survey expansion accessible by the keyboard.

---

EdFi.Buzz.UI/src/Feature/StudentRoster/studentCard.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyMetadataUI.tsx

You can tab through the actual survey cards. If a card is selected and the user press enter, it should redirect to survey answers detail page.

[FIF-336] The survey viewer needs to have the surveys accessible by the keyboard

---

EdFi.Buzz.UI/src/Components/DataTable/dataTable.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyAnswersSummary.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyChartAndTable.tsx

Survey  'View Answers by Student' link accesible by tabs
1 Enter the Surveys menu.
2 Select a section with surveys and select a survey.
3 On the answers detail page, when the chart are displayed, use the tab to navigate.
4 You must be able to access, through the tab, the 'View Answers by Student' link. If you press enter the tables are displayed.
5 You can navigate in the tables, both in the header, and in the student link, using the tab.

[FIF-337] Added tab navigation Survey answer page.

---

EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyChartAndTable.tsx
EdFi.Buzz.UI/src/Feature/SurveyAnalytics/surveyWordCloud.tsx

1. Select a survey that displays a word cloud.
2. When selecting the answers, the detail will be filtered by the answer, when clicking on it, the filter is removed.

[FIF-331] Word cloud updated to be click-able to filter results

---

EdFi.Buzz.UI/src/Feature/AdminSurvey/index.tsx

In order to test this we need to check that deleting a survey works.
1. Go to the admin survey page.
2. Click the delete button.
A modal should be shown with Yes and No buttons. 
3. Click Yes to confirm that the survey is deleted.
Additionally check that the accessibility works as well.

[FIF-373] Fixes the delete survey modal on the admin survey page.

---

EdFi.Buzz.Database/migrations/sample-data/sqls/20201022195215-adds-sample-data-up.sql
EdFi.Buzz.Etl/config/dsHelper.js
EdFi.Buzz.Etl/config/etl.js
EdFi.Buzz.Etl/sql/amt/0009-ImportChronicAbsenteeismData.sql
EdFi.Buzz.Etl/sql/ods/0009-ImportChronicAbsenteeismData.sql
EdFi.Buzz.Etl/src/dbETL.js
EdFi.Buzz.Etl/src/loadMsSqlData.js

1. In your env file set the BUZZ_SQLSOURCE value to ods. Chronic absenteeism data is not imported.
2. In your env file set the BUZZ_SQLSOURCE value to amt, and in your ODS_DBNAME select a database with AMT but without the chrab_ChronicAbsenteeismAttendanceFact View. Chronic absenteeism data is not imported.
3. In your env file set the BUZZ_SQLSOURCE value to amt, and in your ODS_DBNAME select a database with AMT and with the chrab_ChronicAbsenteeismAttendanceFact View. Chronic absenteeism data is imported this time.
On an empty database, execute yarn migrate first, to execute the migrations, and then execute yarn sample-data. Notice that some sample data for the attendance table is inserted.

[FIF-352] Includes chronic absenteeism data from AMT in the ETL scripts.

---

EdFi.Buzz.Installer/eng/README.md
EdFi.Buzz.Installer/eng/Windows/example.configuration.json

This PR updates the Installer Readme to include the usage notes for the api corsOrigins setting. The example configuration.json file is also updated.

[FIF-327] Update readme notes for CORS

---

EdFi.Buzz.UI/eng/windows/install.ps1
EdFi.Buzz.UI/src/Models/Environment.ts
EdFi.Buzz.UI/src/Services/EnvironmentService.ts

We have, in our env file a setting to specify if the image should be loaded from the local assets or from an external source. This setting was not being used properly. These changes fix this problem.
In the env file change the setting for **REACT_APP_EXTERNAL_LOGO** to false.
Then for **REACT_APP_TITLE_LOGO** setting set a local image from the assets folder. 
Now, log in to the app, go to the student detail page for any student.
Finally, refresh the page and the image should be shown properly.
Now, do the same, but this time change the settings so an external image is used instead of a local one. And the image should be shown properly again.
After testing this on the local development environment. Use the installer to install at least the UI, to confirm it works with the installer app as …

[FIF-380] Fixes broken image icon in header of student detail section.

---

EdFi.Buzz.Api/eng/Windows/install.ps1
EdFi.Buzz.Installer/eng/README.md
EdFi.Buzz.Installer/eng/Windows/Application/appinstalls.psm1
EdFi.Buzz.Installer/eng/Windows/example.configuration.json
EdFi.Buzz.Installer/eng/Windows/install.ps1

When merged, this PR will add the ability to configure NODE_EXTRA_CA_CERTS and NODE_TLS_REJECT_UNAUTHORIZED using configuration.json api variables. It also adds the two new settings to the installer readme.
NOTE: The NODE_TLS_REJECT_UNAUTHORIZED defaults to true.
Open the installer readme, you should see notes in API for the two new settings.
> IMPORTANT: Before the following install tests, do not forget to build the new API installer package with test.ps1 in the root.
1. Set api:rejectTlsUnauthorized to false. and api:enableCaCerts to `null` in your configuration.json and run the installer.
2. Run the installer
3. Open API .env file and confirm that the NODE_TLS_REJECT_UNAUTHORIZED is 0 and there is a blank line beneath and no NODE_EXTRA_CA_CERTS setting.
1. Set api:rejectTlsUnauthorized …

[FIF-381] Adds CA cert and TLS reject settings to API installer

---

EdFi.Buzz.Database/migrations/sqls/20201201170923-alter-studentasssessment-up.sql

gen_random_uuid() is needed to create keys. This functions is required and the cascade is for objects that depend on it - when it already exists.
NOTE: The CASCADE was added to ensure that it can drop when existing objects depend on it. I believe this happened initially when the buzz.studentassessment table already had an studentassessmentkey that depended on that same extension
- On your local database, you can drop existing objects and re-run the migration.
- Run the following to drop all data and buzz schema objects...
```sql
DROP SCHEMA IF EXISTS buzz CASCADE;
DELETE FROM PUBLIC.migrations;
```
- In EdFi.Buzz.Database, run the migration...
```bash
yarn run migrate
```
- Expect the migration to complete successfully, and re-populate the database with sample data.

[FIF-384] Drop and create pgcrypto to generate UUID function

---

EdFi.Buzz.Api/package.json
EdFi.Buzz.Api/yarn.lock

Address the dependabot alert to upgrade highlight.js to 10.4.1

[FIF-387] Upgrade highlight.js to 10.4.1

---

EdFi.Buzz.UI/eng/web.config

When merged, this PR allows IIS to serve manifest.json and woff2 file extensions without throwing a 404 error.
> **NOTE:** To test, you need to be running the IIS hosted site.
- Go to [Buzz on Staging](https://buzz-stg.ed-fi.org) now - as it should present the error.
- Load Buzz UI with Developer console open.
- Expect to see HTTP 404 errors for the woff2.
- Go to [Buzz on Production](https://buzz-demo.ed-fi.org) now - as it should present the error.
- Load Buzz UI with Developer console open to the Application tab.
- Expect to see HTTP 404 errors for manifest.json.
- Check out FIF-379 and install. 
- Load Buzz UI **_from IIS_** with Developer console open.
- Expect that 404s are gone.

[FIF-379] Add missing static content to UI web config

---

EdFi.Buzz.UI/src/Feature/AdminSurvey/index.tsx

The Admin Survey page has a bug when loading. The new spinner widget shows but nothing loads. When you open the Developer Tools console or have the API loaded in a console, you can see a loop of requests to our graphql endpoint firing in rapid succession.
Additionally, the page will throw an exception if there are no surveys in the database.
The page should load without issue regardless of how many surveys are in the database.
Given that you are an admin survey loader enabled user and there are survey records,
When click the Admin Surveys menu link as an admin survey user,
It should show the spinner briefly 
And then it should load the page
> NOTE: To remove data, run the following SQL:
```sql
DELETE FROM buzz.studentsurveyanswer;
DELETE FROM buzz.studentsurvey;
DELETE FROM …
```

[FIF-393] Fix admin survey load screen bug
